// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtv_Pti9LeKTg1SfIJGpaTbGOVjRYsn8',
    appId: '1:889180555557:web:1b9c2e96b14f638242f2cc',
    messagingSenderId: '889180555557',
    projectId: 'caseirinho-doces',
    authDomain: 'caseirinho-doces.firebaseapp.com',
    storageBucket: 'caseirinho-doces.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxkBzP-5OWRa0QQz5YNjW2NIgrux2W_k',
    appId: '1:889180555557:android:d43a22f39cceae0742f2cc',
    messagingSenderId: '889180555557',
    projectId: 'caseirinho-doces',
    storageBucket: 'caseirinho-doces.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqJuRekOoIijO6CmpAFih8b94DToh_O8',
    appId: '1:889180555557:ios:a727b49bc17173a142f2cc',
    messagingSenderId: '889180555557',
    projectId: 'caseirinho-doces',
    storageBucket: 'caseirinho-doces.firebasestorage.app',
    iosClientId: '889180555557-jbq588287l250t49v1q5k525ogdsdm90.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseirinhodoces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqJuRekOoIijO6CmpAFih8b94DToh_O8',
    appId: '1:889180555557:ios:a727b49bc17173a142f2cc',
    messagingSenderId: '889180555557',
    projectId: 'caseirinho-doces',
    storageBucket: 'caseirinho-doces.firebasestorage.app',
    iosClientId: '889180555557-jbq588287l250t49v1q5k525ogdsdm90.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseirinhodoces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHtv_Pti9LeKTg1SfIJGpaTbGOVjRYsn8',
    appId: '1:889180555557:web:edd0981a7f577b5842f2cc',
    messagingSenderId: '889180555557',
    projectId: 'caseirinho-doces',
    authDomain: 'caseirinho-doces.firebaseapp.com',
    storageBucket: 'caseirinho-doces.firebasestorage.app',
  );
}
